apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: vault
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: aws-ebs-csi
  resources:
    requests:
      storage: 4Gi